--- #YAML:1.0
name: DBIx-Log4perl
abstract: Log all Perl DBI calls Log::Log4perl
version: 0.22
version_from: lib/DBIx/Log4perl.pm
author:
  - Martin J. Evans
license: perl
distribution_type: module
requires:
    DBI:                           1.5
    Log::Log4perl:                 1.04
    Test::More:                    0.62
build_requires:
  DBI: 1.21
configure_requires:
  DBI: 1.21
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-Log4perl
installdirs:  site
keywords:
  - DBI
  - DBD
  - DBIx
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Martin J. Evans
# ensure there is a newline at the end of this file or pause objects
