# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Log4perl
version:      0.08
version_from: lib/DBIx/Log4perl.pm
installdirs:  site
requires:
    DBI:                           1.5
    Log::Log4perl:                 1.04
    Test::More:                    0.62

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
